% Change directory
function cdir

% Add paths
addpath(...
genpath('Classification'),...
genpath('Unmixing'),...
genpath('HSI'),...
... Support
'Support/Classification/SVM',...
'Support/Classification/SVM/windows',...
'Support/profiles_attri',...
'Support/profiles_morpho',...
'Support/AO-ADMM',...
'Support/tens_compress',...
'Support/Sandia_tensor_toolbox_2',...
'Support/tensorlab_toolbox_2016'...
);

end
